# ASP.NET 
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

# trigger:
# - master
# name: '$(Date:dd-MM-yyyy).$(Rev:r)'
# jobs:
# - job: Windows
#   pool:
#    vmImage: 'windows-latest'
#   variables:
#     solution: '**/*.sln'
#     buildPlatform: 'Any CPU'
#     buildConfiguration: 'Release'
#   steps:
#   - task: DotNetCoreCLI@2
#     displayName: 'publish MyWebApp'
#     inputs:
#       command: 'publish'
#       publishWebProjects: false
#       projects: 'src/MyWebApp.sln'
#       arguments: '-c Release -o $(Build.ArtifactStagingDirectory)'
#       zipAfterPublish: false
#       modifyOutputPath: false
#   - task: VSTest@2
#     displayName: 'Testes Unitarios'
#     inputs:
#       testSelector: 'testAssemblies'
#       testAssemblyVer2: |
#         **\*tests*.dll
#         !**\*TestsAdapter.dll
#         !**\obj\**
#       searchFolder: '$(System.DefaultWorkingDirectory)'
#       platform: '$(buildPlatform)'
#       configuration: '$(buildConfiguration)'
#   - task: CopyFiles@2
#     displayName: 'Copy Arquivos'
#     inputs:
#       SourceFolder: '$(System.DefaultWorkingDirectory)'
#       Contents: |
#         Dockerfile
#         docker-compose.yml
#       TargetFolder: '$(Build.ArtifactStagingDirectory)'
#       OverWrite: true
#   - task: PublishBuildArtifacts@1
#     displayName: 'Publica Artefato'
#     inputs:
#       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#       ArtifactName: 'Pacote'
#       publishLocation: 'Container'
